In [1]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
    return str_text 

In [2]:
d = read_file("files/dl/moby_dick_four_chapters.txt")

# tokenize

In [3]:
import spacy
nlp = spacy.load('en_core_web_lg', disable=['parser', 'tagger', 'ner'])

nlp.max_length = 1198623

In [4]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [5]:
# d = read_file('files/dl/melville-moby_dick.txt')
tokens = separate_punc(d)

/Users/ujjwal/codingpoint/pycourses/venvnlp/lib/python3.11/site-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [6]:
tokens

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such',
 'an',
 'upper',
 'hand',
 '

In [7]:
len(tokens)

11338

In [8]:
train_len = 25+1

In [9]:
text_sequences = []

for i in range(train_len, len(tokens)):

    seq = tokens[i-train_len: i]
    text_sequences.append(seq)



In [10]:
' '.join(text_sequences[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [11]:
' '.join(text_sequences[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [12]:
' '.join(text_sequences[2])

'ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i'

In [13]:
len(text_sequences)

11312

# KERAS

In [14]:
import keras

In [15]:
dir(keras)

['DTypePolicy',
 'FloatDTypePolicy',
 'Function',
 'Initializer',
 'Input',
 'InputSpec',
 'KerasTensor',
 'Layer',
 'Loss',
 'Metric',
 'Model',
 'Operation',
 'Optimizer',
 'Quantizer',
 'Regularizer',
 'Sequential',
 'StatelessScope',
 'Variable',
 '__all__',
 '__builtins__',
 '__cached__',
 '__dir__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'activations',
 'applications',
 'backend',
 'callbacks',
 'config',
 'constraints',
 'datasets',
 'device',
 'distribution',
 'dtype_policies',
 'export',
 'initializers',
 'layers',
 'legacy',
 'losses',
 'metrics',
 'mixed_precision',
 'models',
 'name_scope',
 'ops',
 'optimizers',
 'preprocessing',
 'quantizers',
 'random',
 'regularizers',
 'saving',
 'tree',
 'utils',
 'version']

In [16]:
import keras.preprocessing

In [17]:
dir(keras.preprocessing)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'image',
 'image_dataset_from_directory',
 'sequence',
 'text_dataset_from_directory',
 'timeseries_dataset_from_array']

In [18]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [19]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [20]:
sequences[0]

[956,
 14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 314,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2713,
 14,
 24]

In [21]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'at',
 18: 'this',
 19: 'you',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'on',
 25: 'be',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'about',
 38: 'no',
 39: 'into',
 40: 'by',
 41: 'were',
 42: 'out',
 43: 'or',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'have',
 48: 'an',
 49: 'upon',
 50: 'little',
 51: 'some',
 52: 'old',
 53: 'like',
 54: 'if',
 55: 'they',
 56: 'would',
 57: 'do',
 58: 'over',
 59: 'landlord',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: "n't",
 65: 'night',
 66: 'here',
 67: 'head',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'time',
 74: 'other',
 75: 'very',
 76: 'go',
 77: 'these',
 78: 'more',
 79: 'though',
 80: 'first',
 81: 'sort',


In [22]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

956 : call
14 : me
263 : ishmael
51 : some
261 : years
408 : ago
87 : never
219 : mind
129 : how
111 : long
954 : precisely
260 : having
50 : little
43 : or
38 : no
314 : money
7 : in
23 : my
546 : purse
3 : and
150 : nothing
259 : particular
6 : to
2713 : interest
14 : me
24 : on


In [23]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1003),
             ('money', 120),
             ('in', 5647),
             ('my', 1786),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7150),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 416),
             ('the', 15540),
             ('watery', 26),
  

In [24]:
vocab_size = len(tokenizer.word_counts)

In [25]:
print(vocab_size)

2718


In [26]:
import numpy as np

In [27]:
sequences = np.array(sequences)

In [28]:
sequences

array([[ 956,   14,  263, ..., 2713,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2712, ...,   53,    2, 2718],
       [ 166, 2712,    3, ...,    2, 2718,   26]])

In [29]:
import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding

In [76]:
def create_model(vocab_size, seq_len):
    model = Sequential()
    units = seq_len * 6
    model.add(Embedding(vocab_size, seq_len))
    model.add(LSTM(units, return_sequences=True))
    model.add(LSTM(units))
    model.add(Dense(units, activation='relu'))

    model.add(Dense(vocab_size, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    model.summary()

    return model

In [31]:
from keras.utils import to_categorical


In [32]:
sequences

array([[ 956,   14,  263, ..., 2713,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2712, ...,   53,    2, 2718],
       [ 166, 2712,    3, ...,    2, 2718,   26]])

In [36]:
X = sequences[:,:-1]
X

array([[ 956,   14,  263, ...,    6, 2713,   14],
       [  14,  263,   51, ..., 2713,   14,   24],
       [ 263,   51,  261, ...,   14,   24,  957],
       ...,
       [ 952,   12,  166, ...,   11,  262,   53],
       [  12,  166, 2712, ...,  262,   53,    2],
       [ 166, 2712,    3, ...,   53,    2, 2718]])

In [37]:
y = sequences[:, -1]
y

array([  24,  957,    5, ...,    2, 2718,   26])

In [39]:
y = to_categorical(y, num_classes=vocab_size+1)

In [40]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
y.shape

(11312, 2719)

In [42]:
seq_len = X.shape[1]
seq_len

25

# Training the model


In [77]:
model = create_model(vocab_size+1, seq_len)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
from pickle import dump, load

In [78]:
model.fit(X, y, batch_size=128, epochs=300, verbose=1)

Epoch 1/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 64ms/step - accuracy: 0.0481 - loss: 7.1901
Epoch 2/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 6s 73ms/step - accuracy: 0.0520 - loss: 6.3449
Epoch 3/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - accuracy: 0.0525 - loss: 6.2414
Epoch 4/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 76ms/step - accuracy: 0.0503 - loss: 6.1473
Epoch 5/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 73ms/step - accuracy: 0.0595 - loss: 5.9656
Epoch 6/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 6s 73ms/step - accuracy: 0.0629 - loss: 5.8205
Epoch 7/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - accuracy: 0.0679 - loss: 5.7595
Epoch 8/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 77ms/step - accuracy: 0.0709 - loss: 5.6801
Epoch 9/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 76ms/step - accuracy: 0.0710 - loss: 5.5734
Epoch 10/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 76ms/step - accuracy: 0.0766 - loss: 5.4863
Epoch 11/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 75ms/step - accuracy: 0.0778 - loss: 5.4702
Epoch 12/300
89/89 ━━━━━━━━━━━━━━━━━━━━ 7s 75ms/step

In [79]:
model.save("files/dl/epochs3006t.keras")

In [80]:
dump(tokenizer, open("files/dl/epochs300_6t", "wb"))

# generating new text

In [81]:
from random import randint
from pickle import load

from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [82]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    output_text = []
    input_text = seed_text

    for i in range(num_gen_words):
        encoded_txt = tokenizer.texts_to_sequences([input_text])[0]
        pad_encoded = pad_sequences([encoded_txt], maxlen=seq_len, truncating='pre')
        word_predictions = model.predict(pad_encoded, verbose=0)
        pred_word_ind = word_predictions.argmax(axis=1)[0]
        pred_word = tokenizer.index_word[pred_word_ind]
        input_text += ' ' + pred_word
        output_text.append(pred_word)

    return ' '.join(output_text)

In [57]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [83]:
def get_random_text_seq():
    import random
    return text_sequences[random.randint(0, len(text_sequences))]

In [90]:
seed_text = get_random_text_seq()
seed_text

['indeed',
 'partly',
 'lying',
 'on',
 'it',
 'as',
 'the',
 'arm',
 'did',
 'when',
 'i',
 'first',
 'awoke',
 'i',
 'could',
 'hardly',
 'tell',
 'it',
 'from',
 'the',
 'quilt',
 'they',
 'so',
 'blended',
 'their',
 'hues']

In [91]:
generate_text(model, tokenizer, seq_len, seed_text, num_gen_words=15)

'together says bird look look look look look look look look look look look look'

In [92]:
model_big = load_model("files/dl/epochs3006t.keras")